In [2]:
#importer les librairies
import numpy as np
import  pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
Data=pd.read_csv('jobs_in_data.csv')
Data.duplicated().sum()
Data.drop_duplicates(inplace=True)


In [4]:
X=Data.drop(['salary_in_usd'],axis=1)
Y=Data['salary_in_usd']

In [5]:
Data


work_year                 job_title                    job_category  \
0          2023      Data DevOps Engineer                Data Engineering   
1          2023            Data Architect  Data Architecture and Modeling   
2          2023            Data Architect  Data Architecture and Modeling   
3          2023            Data Scientist       Data Science and Research   
4          2023            Data Scientist       Data Science and Research   
...         ...                       ...                             ...   
9350       2021           Data Specialist    Data Management and Strategy   
9351       2020            Data Scientist       Data Science and Research   
9352       2021  Principal Data Scientist       Data Science and Research   
9353       2020            Data Scientist       Data Science and Research   
9354       2020     Business Data Analyst                   Data Analysis   

     salary_currency  salary  salary_in_usd employee_residence  \
0                EUR   88000          95012            Germany   
1                USD  186000         186000      United States   
2                USD   81800          81800      United States   
3                USD  212000         212000      United States   
4                USD   93300          93300      United States   
...              ...     ...            ...                ...   
9350             USD  165000         165000      United States   
9351             USD  412000         412000      United States   
9352             USD  151000         151000      United States   
9353             USD  105000         105000      United States   
9354             USD  100000         100000      United States   

     experience_level employment_type work_setting company_location  \
0           Mid-level       Full-time       Hybrid          Germany   
1              Senior       Full-time    In-person    United States   
2              Senior       Full-time    In-person    United States   
3              Senior       Full-time    In-person    United States   
4              Senior       Full-time    In-person    United States   
...               ...             ...          ...              ...   
9350           Senior       Full-time       Remote    United States   
9351           Senior       Full-time       Remote    United States   
9352        Mid-level       Full-time       Remote    United States   
9353      Entry-level       Full-time       Remote    United States   
9354      Entry-level        Contract       Remote    United States   

     company_size  
0               L  
1               M  
2               M  
3               M  
4               M  
...           ...  
9350            L  
9351            L  
9352            L  
9353            S  
9354            L  

[5341 rows x 12 columns]

In [6]:
Data

work_year                 job_title                    job_category  \
0          2023      Data DevOps Engineer                Data Engineering   
1          2023            Data Architect  Data Architecture and Modeling   
2          2023            Data Architect  Data Architecture and Modeling   
3          2023            Data Scientist       Data Science and Research   
4          2023            Data Scientist       Data Science and Research   
...         ...                       ...                             ...   
9350       2021           Data Specialist    Data Management and Strategy   
9351       2020            Data Scientist       Data Science and Research   
9352       2021  Principal Data Scientist       Data Science and Research   
9353       2020            Data Scientist       Data Science and Research   
9354       2020     Business Data Analyst                   Data Analysis   

     salary_currency  salary  salary_in_usd employee_residence  \
0                EUR   88000          95012            Germany   
1                USD  186000         186000      United States   
2                USD   81800          81800      United States   
3                USD  212000         212000      United States   
4                USD   93300          93300      United States   
...              ...     ...            ...                ...   
9350             USD  165000         165000      United States   
9351             USD  412000         412000      United States   
9352             USD  151000         151000      United States   
9353             USD  105000         105000      United States   
9354             USD  100000         100000      United States   

     experience_level employment_type work_setting company_location  \
0           Mid-level       Full-time       Hybrid          Germany   
1              Senior       Full-time    In-person    United States   
2              Senior       Full-time    In-person    United States   
3              Senior       Full-time    In-person    United States   
4              Senior       Full-time    In-person    United States   
...               ...             ...          ...              ...   
9350           Senior       Full-time       Remote    United States   
9351           Senior       Full-time       Remote    United States   
9352        Mid-level       Full-time       Remote    United States   
9353      Entry-level       Full-time       Remote    United States   
9354      Entry-level        Contract       Remote    United States   

     company_size  
0               L  
1               M  
2               M  
3               M  
4               M  
...           ...  
9350            L  
9351            L  
9352            L  
9353            S  
9354            L  

[5341 rows x 12 columns]

In [7]:
X

work_year                 job_title                    job_category  \
0          2023      Data DevOps Engineer                Data Engineering   
1          2023            Data Architect  Data Architecture and Modeling   
2          2023            Data Architect  Data Architecture and Modeling   
3          2023            Data Scientist       Data Science and Research   
4          2023            Data Scientist       Data Science and Research   
...         ...                       ...                             ...   
9350       2021           Data Specialist    Data Management and Strategy   
9351       2020            Data Scientist       Data Science and Research   
9352       2021  Principal Data Scientist       Data Science and Research   
9353       2020            Data Scientist       Data Science and Research   
9354       2020     Business Data Analyst                   Data Analysis   

     salary_currency  salary employee_residence experience_level  \
0                EUR   88000            Germany        Mid-level   
1                USD  186000      United States           Senior   
2                USD   81800      United States           Senior   
3                USD  212000      United States           Senior   
4                USD   93300      United States           Senior   
...              ...     ...                ...              ...   
9350             USD  165000      United States           Senior   
9351             USD  412000      United States           Senior   
9352             USD  151000      United States        Mid-level   
9353             USD  105000      United States      Entry-level   
9354             USD  100000      United States      Entry-level   

     employment_type work_setting company_location company_size  
0          Full-time       Hybrid          Germany            L  
1          Full-time    In-person    United States            M  
2          Full-time    In-person    United States            M  
3          Full-time    In-person    United States            M  
4          Full-time    In-person    United States            M  
...              ...          ...              ...          ...  
9350       Full-time       Remote    United States            L  
9351       Full-time       Remote    United States            L  
9352       Full-time       Remote    United States            L  
9353       Full-time       Remote    United States            S  
9354        Contract       Remote    United States            L  

[5341 rows x 11 columns]

In [8]:
#Gérer les variables catégorique
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 
ct=ColumnTransformer(
    transformers=[
        ('job_title', OneHotEncoder(), ['job_title']),
        ('job_category', OneHotEncoder(), ['job_category']),
        ('salary_currency', OneHotEncoder(), ['salary_currency']),
        ('employee_residence', OneHotEncoder(), ['employee_residence']),
        ('experience_level', OneHotEncoder(), ['experience_level']),
        ('employment_type', OneHotEncoder(), ['employment_type']),
        ('work_setting', OneHotEncoder(), ['work_setting']),
        ('company_location', OneHotEncoder(), ['company_location']),
        ('company_size', OneHotEncoder(), ['company_size'])
    ],
    remainder='passthrough'
)
X=ct.fit_transform(X)

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Assuming 'data' is your DataFrame
numerical_columns = Data.select_dtypes(exclude=['object']).columns
object_columns = Data.select_dtypes(include=['object']).columns

# Standardize numerical columns (if any)
scaler = StandardScaler()
Data[numerical_columns] = scaler.fit_transform(Data[numerical_columns])


In [10]:
print(X.toarray())

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.023e+03 8.800e+04]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.023e+03 1.860e+05]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.023e+03 8.180e+04]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.021e+03 1.510e+05]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 2.020e+03 1.050e+05]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.020e+03 1.000e+05]]


In [11]:
#Diviser le dataset(20% pour le test)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=42)

In [12]:
print(X_train.toarray())

[[     0.      0.      0. ...      0.   2023. 109000.]
 [     0.      0.      0. ...      0.   2023. 134000.]
 [     0.      0.      0. ...      0.   2023. 220000.]
 ...
 [     0.      0.      0. ...      0.   2020.  88000.]
 [     0.      0.      0. ...      0.   2021. 110000.]
 [     0.      0.      0. ...      0.   2023. 112000.]]


In [13]:
print(X_test.toarray())

[[     0.      0.      0. ...      0.   2023. 220000.]
 [     0.      0.      0. ...      0.   2023. 139000.]
 [     0.      0.      0. ...      0.   2021. 165000.]
 ...
 [     0.      0.      0. ...      0.   2023.  87000.]
 [     0.      0.      0. ...      0.   2023. 130000.]
 [     0.      0.      0. ...      0.   2023. 210000.]]


In [14]:
#construire le modéle
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [15]:
#faire des prédictions 
Y_pred=regressor.predict(X_test)

In [16]:
Y_pred

array([220293.24373449, 138396.46742027, 164884.85442965, ...,
        90706.13920641, 133561.07190706, 208285.44980038])

In [17]:
Y_test

5878    220000
2891    139000
9350    165000
7771     95000
179     224800
         ...  
786     120000
8570    200000
7309     87000
1883    130000
125     210000
Name: salary_in_usd, Length: 1069, dtype: int64

In [18]:
#Calcul des métrique d'évaluation
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# RMSE (Root Mean Squared Error)
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))

In [19]:
# MAE (Mean Absolute Error)
mae = mean_absolute_error(Y_test, Y_pred)

In [20]:
# R² (Coefficient de détermination)
r2 = r2_score(Y_test, Y_pred)

In [21]:
print("RMSE:", rmse)

RMSE: 12749.296876407197


In [22]:
print("MAE:", mae)

MAE: 3042.350395204639


In [23]:
print("R²:", r2)

R²: 0.9615277124704762


In [24]:
from joblib import dump

# Sauvegarder le modèle
dump(regressor, 'modele_regression.pkl')

['modele_regression.pkl']